# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b75033e2b61c42807766b4106b9a62197379c7cbd49aecc7da86f2aaf3007f4d8bee528fb97f6aec11276d042ce68dcdae4dc44d616a7a4df2f698a987223d7b

test:
  secret_key_base: b125c74b6580ce5a1239e8d59181626d77eaa95be4759a5d933396a2662b4a87927fe0a17171db56f0cfb28f22c4db083c12f9f9b87963008743bb3881f6addc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
